### ISSUE TITLE
Remove Google Tracker Rule (EC532)

### ISSUE THREAD

**Issue by pbaumard** [green-code-initiative/ecoCode-android#94]
**Problem**

Google Tracker Rule (EC532) is not related to the purpose of the ecoCode-android project which it from the [README](https://github.com/green-code-initiative/ecoCode-android/blob/main/README.md) to provide:

>  static code analyzers to highlight code structures that may have a negative ecological impact

**Solution**

Remove Google Tracker Rule (EC532)

**Additional context**

I believe this out-of-scope rule about privacy and not about eco-design is coming from the confusion about [Mobile-specific Best Practices](https://github.com/cnumr/best-practices-mobile) which are not only about _Environmental Code Smells_ but also about _Social Code Smells_. Only the first category should be considered for this project which is included in the [green-code-initiative](https://github.com/green-code-initiative) which purpose is: "Let's write low-carbon software".

**Comment by olegoaer** [comment]
Your point is well taken. It's a **social** smell, not an **environmental** smell, and [implemented as such](https://github.com/green-code-initiative/ecoCode-android/tree/main/android-plugin/src/main/java/io/ecocode/java/checks/social/privacy). This type of smell is a side concern and is not the primary aim of the green code initiative.

But its presence in the ecoCode Android plugin serves as a **proof of concept** towards _sustainability_ (environment + social). I personally use it in my live demos, and the custom GUI already takes this into account (see screenshot). That's why they have to stay here for the time being.

<img width="959" alt="Capture d’écran 2024-08-13 à 10 08 01" src="https://github.com/user-attachments/assets/632b2e8e-c02a-4303-a9d6-56b9a11002cf">
